service: manage-project-app-api

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  # Set the table name here so we can use it while testing locally
  tableName: ${self:custom.stage}-project
  # Set our DynamoDB throughput for prod and all other non-prod stages.
  tableThroughputs:
    prod: 5
    default: 1
  tableThroughput: ${self:custom.tableThroughputs.${self:custom.stage}, self:custom.tableThroughputs.default}
  # Load our webpack config
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  # Load our secret environment variables based on the current stage.
  # Fallback to default if it is not in prod.
  environment: ${file(env.yml):${self:custom.stage}, file(env.yml):default}

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: eu-west-2

  # These environment variables are made available to our functions
  # under process.env.
  environment:
    tableName: ${self:custom.tableName}
    stripeSecretKey: ${self:custom.environment.stripeSecretKey}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      # Restrict our IAM role permissions to
      # the specific table for the stage
      Resource: "arn:aws:dynamodb:eu-west-2:*:*"

functions:
  # Defines an HTTP API endpoint that calls the main function in create.js
  # - path: url path is /notes
  # - method: POST request
  # - cors: enabled CORS (Cross-Origin Resource Sharing) for browser cross
  #     domain api call
  # - authorizer: authenticate using the AWS IAM role
  createProject:
    handler: createProject.main
    events:
      - http:
          path: project
          method: post
          cors: true
          authorizer: aws_iam
  getProject:
    # Defines an HTTP API endpoint that calls the main function in get.js
    # - path: url path is /notes/{id}
    # - method: GET request
    handler: getProject.main
    events:
      - http:
          path: project/{id}
          method: get
          cors: true
          authorizer: aws_iam
  listProject:
    # Defines an HTTP API endpoint that calls the main function in list.js
    # - path: url path is /notes
    # - method: GET request
    handler: listProject.main
    events:
      - http:
          path: project
          method: get
          cors: true
          authorizer: aws_iam 
  updateProject:
    # Defines an HTTP API endpoint that calls the main function in update.js
    # - path: url path is /notes/{id}
    # - method: PUT request
    handler: updateProject.main
    events:
      - http:
          path: project/{id}
          method: put
          cors: true
          authorizer: aws_iam
  deleteProject:
    # Defines an HTTP API endpoint that calls the main function in delete.js
    # - path: url path is /notes/{id}
    # - method: DELETE request
    handler: deleteProject.main
    events:
      - http:
          path: project/{id}
          method: delete
          cors: true
          authorizer: aws_iam
  createUser:
    handler: createUser.main
    events:
      - http:
          path: user
          method: post
          cors: true
          authorizer: aws_iam
  getUser:
    handler: getUser.main
    events:
      - http:
          path: user/{id}
          method: get
          cors: true
          authorizer: aws_iam
  listUser:
    # Defines an HTTP API endpoint that calls the main function in list.js
    # - path: url path is /notes
    # - method: GET request
    handler: listUser.main
    events:
      - http:
          path: user
          method: get
          cors: true
          authorizer: aws_iam
  updateUser:
    handler: updateUser.main
    events:
      - http:
          path: user/{id}
          method: put
          cors: true
          authorizer: aws_iam 
  deleteUser:
    handler: deleteUser.main
    events:
      - http:
          path: user/{id}
          method: delete
          cors: true
          authorizer: aws_iam

# Create our resources with separate CloudFormation templates
resources:
  # DynamoDB
  - ${file(resources/dynamodb-table.yml)}
  # S3
  - ${file(resources/s3-bucket.yml)}
  # Cognito
  - ${file(resources/cognito-user-pool.yml)}
  - ${file(resources/cognito-identity-pool.yml)}
  
  
 